### PR TITLE
Set limitation for model mapping

### PR DESCRIPTION
**Pull request by changwangss**
## Type of Change

the mapping is only used  for IPEX 2.0 smoothquant.
the root cause is 
1. the tensors on both sides of the plus sign cannot be recognized when tracing.
2. example_inputs only support tuple, the order in tuple should be the same with forward parameters order.

If you use torch.jit.trace in other situations, you may also need this mapping, please let me know.
## Description

change description: 
Advance the order of processing sq_config and load the fp32 model with special processing for sq.
## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Review by XinyuYe-Intel — APPROVED** [review]

**Comment by changwangss** [comment]
@VincyZhang the CI PR ut is canceled, it seems due to no space, please check.

**Comment by VincyZhang** [comment]
> @VincyZhang the CI PR ut is canceled, it seems due to no space, please check.

This is not due to space, just hangs, it's strange that can not import tensorflow after importing torch. See this issue, https://github.com/tensorflow/tensorflow/issues/60109

**Comment by VincyZhang** [comment]
@changwangss  you can ask @PenghuiCheng for help, he solved this problem before.

**Comment by hshen14** [comment]
> @changwangss you can ask @PenghuiCheng for help, he solved this problem before.

Lazy import?

**Comment by changwangss** [comment]
close, #568 merged.

**Pull request closed without merging**
