### PR TITLE
[Cpp Graph] Align Cpp Beam Search 

### PR DESCRIPTION
**Pull request by zhentaoyu**
## Type of Change

BUG FIX && Enhancement
Align cpp `beam_search` with HF `transformers` repo implementation

## Description

detail description 
JIRA ticket: [835](https://jira.devtools.intel.com/browse/NLPTOOLKIU-835)

TODO:
- [x] gen len reduction (early stopping) ---> stop gen more repeated text
- [x] deal with eos sentences and test more examples
- [x] accelerate beam score computations (`log_softmax` reductions) while keeping the same value as `transformers`
- [x] add beam search verbose output (debug, usage: `cmake -DBEAM_SEARCH_VERBOSE=ON ..`, example: [log.txt](https://github.com/intel/intel-extension-for-transformers/files/12681039/log.txt)) 
~~- [ ] CI (will be added in another pr by using `pybind` )~~
- [ ] pass MLPerf acc test (Q4_0 offline passed)

## Expected Behavior & Potential Risk

`numactl -l -C 0-55  ./build/bin/pybind_gptj fp32.bin`  && MLPerf offline acc test
acc reference: `"ROUGE1", 42.9865 * 0.99, "ROUGE2", 20.1235 * 0.99, "ROUGEL", 29.9881 * 0.99, "GEN_LEN", 4016878*0.9`
**All TESTS TURN OFF `kv_cache_jblas` BY SETTING `memory_type=KV_MEM_TYPE_F16`**

## How has this PR been tested?

`cpp`: `numactl -l -C 0-55  ./build/bin/pybind_gptj fp32.bin`

`hf`:
```python
from transformers import pipeline, set_seed, AutoModelForCausalLM, AutoTokenizer

model_dir = "finetuned-gptj"
tokenizer = AutoTokenizer.from_pretrained(model_dir)

model = AutoModelForCausalLM.from_pretrained(model_dir)
model.eval()

prompt = "Tell me 10 things about jazz music"
inputs = tokenizer(prompt, return_tensors="pt")

print("inputs", inputs)
generate_ids = model.generate(inputs.input_ids, max_new_tokens=128, min_new_tokens=30, early_stopping=True, num_beams=4)
ans = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print(ans)
```

## Dependency Change?

None

### CODE REVIEW

**Comment by zhentaoyu** [comment]
MLPerf offline acc test results: [bb8d29a](https://github.com/intel/intel-extension-for-transformers/pull/322/commits/bb8d29afa52018cdb0d848b940d2021c680cea17)
`{'rouge1': 43.9659, 'rouge2': 20.2286, 'rougeL': 29.4819, 'rougeLsum': 40.9451, 'gen_len': 200586, 'gen_num': 500}`

**Comment by zhentaoyu** [comment]
scores and top_k tokens comparisons between `cpp` and `hf transformers` (prompt = `"A spaceship lands on the moon"` ):
- `hf transformers`:
```bash
next_tokens: tensor([[  198,   198,   317,   475,   383, 38306,   319,   262]])
next_token_scores: tensor([[-1.4747, -2.2295, -4.0196, -4.0743, -4.5361, -4.9157, -4.9327, -5.1006]])
next_indices: tensor([[1, 0, 0, 2, 0, 2, 3, 2]])
beam_scores:  tensor([-1.4747, -2.2295, -4.0196, -4.0743])
beam_next_tokens: tensor([198, 198, 317, 475])
beam_idx: tensor([1, 0, 0, 2])
.....
......
=========== final==========
best: [tensor([   32, 40663,  8604,   319,   262,  8824,   764,   198,    32, 40663,
          468, 11406,   319,   262,  8824,   764,   198,    32, 40663,   468,
        11406,   319,   262,  8824,   764,   198,    32, 40663,   468, 11406,
          319,   262,  8824,   764,   198,    32, 40663,   468, 11406,   319,
          262,  8824,   764])]
best_score: tensor([-0.1742])
best_indices: [None]
A spaceship lands on the moon .
A spaceship has landed on the moon .
A spaceship has landed on the moon .
A spaceship has landed on the moon .
A spaceship has landed on the moon .
```

- `cpp`:
```bash
13: . 
764:  . 
11: , 
1377:  -- 
====================== 
198: 
, score:  -1.474517, beam_idx: 1 
198: 
, score:  -2.230055, beam_idx: 0 
317:  A, score:  -4.019489, beam_idx: 0 
475:  but, score:  -4.074911, beam_idx: 2 
383:  The, score:  -4.536015, beam_idx: 0 
38306:  sparks, score:  -4.914916, beam_idx: 2 
319:  on, score:  -4.932207, beam_idx: 3 
262:  the, score:  -5.100197, beam_idx: 2 


Current beams:
beams[0]: length: 2, score:    -2.230055, eos: 0, tokens:
13: ., 198: 
, 
beams[1]: length: 2, score:    -4.019489, eos: 0, tokens:
13: ., 317:  A, 
beams[2]: length: 2, score:    -1.474517, eos: 0, tokens:
764:  ., 198: 
, 
beams[3]: length: 2, score:    -4.074911, eos: 0, tokens:
11: ,, 475:  but, 
.....
.....
Final beam:
length: 37, score:    -0.174138, eos: 0, tokens:
764:  ., 198: 
, 32: A, 40663:  spaceship, 468:  has, 11406:  landed, 319:  on, 262:  the, 8824:  moon, 764:  ., 198: 
, 32: A, 40663:  spaceship, 468:  has, 11406:  landed, 319:  on, 262:  the, 8824:  moon, 764:  ., 198: 
, 32: A, 40663:  spaceship, 468:  has, 11406:  landed, 319:  on, 262:  the, 8824:  moon, 764:  ., 198: 
, 32: A, 40663:  spaceship, 468:  has, 11406:  landed, 319:  on, 262:  the, 8824:  moon, 764:  ., 
A spaceship lands on the moon .
A spaceship has landed on the moon .
A spaceship has landed on the moon .
A spaceship has landed on the moon .
A spaceship has landed on the moon .
```

**Comment by zhentaoyu** [comment]
offline test cases for reference (fp32 dtype, `max_new_tokens`=128, `min_new_tokens`=30)
1. prompt = `"Tell me 10 things about jazz music"`
   - `early_stopping`=true
    `hf`: `Tell me 10 things about jazz music and I will tell you 10 things about jazz music.”
           Jazz music is all over the radio and television, but few people understand it .
           This week, jazz music is back on the radio and television in a big way .
           Jazz music is all over the radio and television, but few people understand it .` 
    
     `cpp`: `Tell me 10 things about jazz music and I will tell you 10 things about jazz music.”
               Jazz music is all over the radio and television, but few people understand it .
               This week, jazz music is back on the radio and television in a big way .
               Jazz music is all over the radio and television, but few people understand it .`
   
   - `early_stopping`=false
     `hf`: `Tell me 10 things about jazz music and I will tell you 10 things about jazz music.”
Jazz music is all over the radio and television, but few people understand it .
This week, jazz music is back on the radio and television in the U.S.
Jazz music is all over the radio and television, but few people understand it .
This week, jazz music is back on the radio and television in the U.S.
Jazz music is all over the radio and television, but few people understand it .
This week, jazz music is back on the radio and television in the U.S.
Jazz music` 
    
     `cpp`: `Tell me 10 things about jazz music and I will tell you 10 things about jazz music.”
Jazz music is all over the radio and television, but few people understand it .
This week, jazz music is back on the radio and television in the U.S.
Jazz music is all over the radio and television, but few people understand it .
This week, jazz music is back on the radio and television in the U.S.
Jazz music is all over the radio and television, but few people understand it .
This week, jazz music is back on the radio and television in the U.S.
Jazz music`

2. prompt = `"Once upon a time"`
   - `early_stopping`=true
      `hf`: `Once upon a time...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...`
      
      `cpp`: `Once upon a time...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...`

   - `early_stopping`=false
      `hf`: `Once upon a time...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young`
      
      `cpp`: `Once upon a time...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young and full of hope...
... when the world was young`

3. long prompt = https://github.com/intel/intel-extension-for-transformers/blob/f1d8a054e1f7a246b0b753aadda934447028e723/intel_extension_for_transformers/llm/runtime/graph/application/pybind_gptj.cpp#L230-L306
   - `early_stopping`=true or false
      `hf`: `I mean, I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the`
      
      `cpp`: `I mean, I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the only thing that really mattered was getting it done. I had a lot of talk about what to do, but in the end, the`

**Comment by a32543254** [comment]
consider use extension test to keep this beam search feature acc is good

**Comment by zhentaoyu** [comment]
> consider use extension test to keep this beam search feature acc is good

We should. How about running the `pybind_gptj` binary in CI machine as we testing now, @VincyZhang ?

**Review by zhenwei-intel — APPROVED** [review]

**Review by a32543254 — APPROVED** [review]
LGTM

**Pull request merged**
