### PR TITLE
[CPP Graph] Rename LLM chat application

### PR DESCRIPTION
**Pull request by zhentaoyu**
## Type of Change

change bin name `chat_xxx` to `run_xxx` in `runtime/graph/application`
delete `chat` folder

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

future new CPP model PRs need to follow

## How has this PR been tested?

extension test

## Dependency Change?

None

### CODE REVIEW

**Comment by zhentaoyu** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/70/

**Comment by airMeng** [comment]
they are named as ```chat_xxx``` because they are chatbot application (from llama.cpp), any specific reason to rename?

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by hshen14** [comment]
> they are named as `chat_xxx` because they are chatbot application (from llama.cpp), any specific reason to rename?

more generic name, not limited to chat user scenario

**Review by lzwhard — APPROVED** [review]
LGTM

**Review by zhenwei-intel — APPROVED** [review]
LGTM

**Comment by zhentaoyu** [comment]
> https://github.com/intel/intel-extension-for-transformers/actions/runs/6083023280/job/16502051208?pr=236
> 
> please update validation scripts as well
> 
> https://github.com/intel/intel-extension-for-transformers/blob/4040d2a23b9fd460c812e75487646d4986e0fae1/.github/workflows/script/models/cpp_graph_inference.sh#L20

https://github.com/intel-innersource/frameworks.ai.lpot.lpot-validation/pull/497

**Review by airMeng — APPROVED** [review]

**Pull request merged**
