### PR TITLE
[LLM Runtime] Fix mistral bf16

### PR DESCRIPTION
**Pull request by zhenwei-intel**
## Type of Change

bug fix

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by intellinjun — APPROVED** [review]
LGTM

**Comment by VincyZhang** [comment]
mistral: https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/221/

**Comment by VincyZhang** [comment]
@zhenwei-intel seems failed https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_cpp_graph_test/2235/artifact/launch.log

**Comment by zhenwei-intel** [comment]
> @zhenwei-intel seems failed https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_cpp_graph_test/2235/artifact/launch.log

transformers version should be greater than 4.34.0

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/223/

**Pull request merged**
