### PR TITLE
docs/README.md

### PR DESCRIPTION
**Pull request by RS-labhub**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by RS-labhub** [comment]
@VincyZhang please review the changes

**Review by hshen14 — APPROVED** [review]

**Review by VincyZhang — APPROVED** [review]

**Comment by VincyZhang** [comment]
@RS-labhub  Please resolve conflicts, thanks!

**Comment by RS-labhub** [comment]
> @RS-labhub Please resolve conflicts, thanks!

How to do so?

**Comment by VincyZhang** [comment]
Option 1: resolve conflict on web page, 
image
Option 2: resolve conflict locally
 (1) git fetch
 (2) git rebase main
 (3) git push

**Pull request closed without merging**
