### PR TITLE
fix qbits backend get wrong workspace malloc size when using Release compile Flag

### PR DESCRIPTION
**Pull request by zhewang1-intc**
## Type of Change

feature or bug fix or documentation or others: bug
API changed or not: not

## Description

detail description 
JIRA ticket: https://jira.devtools.intel.com/browse/NLPTOOLKIU-977

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 
qbits int8 compute-type linear can execute normally with Release compile Flag.

## How has this PR been tested?
tested on 335T

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed: no

### CODE REVIEW

**Comment by airMeng** [comment]
BTW, should be ```csrc``` not ```cscr```

**Comment by zhewang1-intc** [comment]
> BTW, should be `csrc` not `cscr`
nice eyesight

**Review by airMeng — APPROVED** [review]

**Comment by VincyZhang** [comment]
UT：https://github.com/intel/intel-extension-for-transformers/actions/runs/6662610298

**Review by a32543254 — APPROVED** [review]
LGTM

**Pull request merged**
