### PR TITLE
improve low bits model loading

### PR DESCRIPTION
**Pull request by changwangss**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1536/

**Review by kevinintel — APPROVED** [review]

**Comment by VincyZhang** [comment]
UT - python3.9: https://inteltf-jenk.sh.intel.com/job/nlp-toolkit-optimize-ut/3015/
UT - python3.10: https://inteltf-jenk.sh.intel.com/job/nlp-toolkit-optimize-ut/3016/

**Comment by VincyZhang** [comment]
GPT-J load-in-4-bit: https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/6473/
Mistral-7B autoround: https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/6474/
Mistral-7B GPTQ Qbits: https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/6477/
Mistral-7B GPTQ NeuralSpeed: https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/6476/

**Comment by VincyZhang** [comment]
Mistral-7B autoround neuralspeed: https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/6483/

**Pull request merged**
