### PR TITLE
[LLM Runtime] integrate AVX_VNNI

### PR DESCRIPTION
**Pull request by yuchengliu1**
## Type of Change

NO API changed or not

integrate AVX_VNNI

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by airMeng** [comment]
@VincyZhang can you deploy extension tests on one of our client machine? @yuchengliu1 can help

**Review by airMeng — APPROVED** [review]

**Comment by yuchengliu1** [comment]
CPU: 12900
compute_type: int32

 

  | first token | next token
-- | -- | --
llama-7B_q4j_perN | 17046.92 ms (16.65 ms per token) | 169.06 ms per token
llama2-7B_q4j_perN | 16952.96 ms (16.56 ms per token) | 166.27 ms per token

**Comment by kevinintel** [comment]
I remembered latency of AVX2 is 141.69ms.
Is 166 ms good enough?

**Comment by airMeng** [comment]
> I remembered latency of AVX2 is 141.69ms. Is 166 ms good enough?

compared with https://github.com/intel/intel-extension-for-transformers/pull/493 161ms

BTW it will be better to list memory bandwidth of your machine @yuchengliu1

**Comment by yuchengliu1** [comment]
> I remembered latency of AVX2 is 141.69ms. Is 166 ms good enough?

141.69ms is the latency of llama.cpp not ITREX, and it was performed on a different machine. Considering the different CPU and memory, a direct comparison would not be appropriate. The machine from #493 seem have a better performance. The next token latency of ITREX q4_0 179.03ms(this PR) VS 136.37ms(#493 ). @VincyZhang and I will run a complete CI on this machine.

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_cpp_graph_test/1445/
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wenxinzh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wenxinzh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Model | AVX VNNI First token  (ms) | AVX VNNI Next token  (ms) | AVX2 First token  (ms) | AVX2 Next token  (ms)
-- | -- | -- | -- | --
LLAMA2-7B-Chat | 17046.92 | 169.06 | 25337.58 | 250.01



</body>

</html>

**Comment by yuchengliu1** [comment]
> https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_cpp_graph_test/1445/
> 
> Model	AVX VNNI First token  (ms)	AVX VNNI Next token  (ms)	AVX2 First token  (ms)	AVX2 Next token  (ms)
> LLAMA2-7B-Chat	17046.92	169.06	25337.58	250.01

llama.cpp ( set thread=16 manually ) performance  on the same matchine.
first token:  39511.79 ms /  1024 tokens (   38.59 ms per token,    25.92 tokens per second)
next token: 5337.70 ms /    31 runs   (  172.18 ms per token,     5.81 tokens per second)

**Pull request merged**
