### PR TITLE
restrain langchain version

### PR DESCRIPTION
**Pull request by VincyZhang**
## Type of Change

temperately restrain component version until we adapt to the latest

### CODE REVIEW

**Comment by VincyZhang** [comment]
@XuhuiRen before adapt to latest langchain, we need to restrain to last stable version

**Review by XuhuiRen — APPROVED** [review]

**Comment by XuhuiRen** [comment]
seems ipex version issue

**Comment by hshen14** [comment]
@VincyZhang  did you see any issue from current langchain version without upgrading?

**Comment by VincyZhang** [comment]
> @VincyZhang did you see any issue from current langchain version without upgrading?

API changed, no "Chroma" in "langchian.vectorstores"

**Review by changwangss — APPROVED** [review]

**Comment by VincyZhang** [comment]
Neuralchat UT is due to IPEX version not match with torch, and fastfaile due to baseline UT has no version controls.

**Pull request merged**
