### PR TITLE
move neural engine to deprecated

### PR DESCRIPTION
**Pull request by zhenwei-intel**
## Type of Change

API changed

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by a32543254 — COMMENTED** [review]
LGTM

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by zhentaoyu — APPROVED** [review]
LGTM

**Comment by VincyZhang** [comment]
UT branch coverage drop -0.105%, checked report due to false positive, UT is okay

**Pull request merged**
