### PR TITLE
[CPP Graph] Opt qbits dequant

### PR DESCRIPTION
**Pull request by zhewang1-intc**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by airMeng** [comment]
jblas commit id?

**Comment by zhewang1-intc** [comment]
> jblas commit id?

f517bb94c5b10f4a8ced82ebc4130d652d707f5d

**Comment by airMeng** [comment]
trigger an extension test

**Comment by zhewang1-intc** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/154/

**Comment by airMeng** [comment]
https://inteltf-jenk.sh.intel.com/blue/organizations/jenkins/ITREX-cpp-graph-extension/detail/ITREX-cpp-graph-extension/155/pipeline/

**Review by airMeng — APPROVED** [review]

**Comment by zhewang1-intc** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/156/

**Review by a32543254 — APPROVED** [review]
LGTM

**Pull request merged**
