### PR TITLE
Added notebook examples for TangoBERT and SWEET

### PR DESCRIPTION
**Pull request by XinyuYe-Intel**
## Type of Change

notebook examples
API not changed

## Description

Added notebook examples for TangoBERT and SWEET.
JIRA ticket: xxx

## Expected Behavior & Potential Risk

pass local test

## How has this PR been tested?

run notebooks

## Dependency Change?

no library dependency introduced or removed

### CODE REVIEW

**Comment by hshen14** [comment]
Where is the entry to get users to the notebook?

**Comment by XinyuYe-Intel** [comment]
> Where is the entry to get users to the notebook?

Where would you think it's suitable?

**Comment by hshen14** [comment]
> > Where is the entry to get users to the notebook?
> 
> Where would you think it's suitable?

Is this about early exit? Add Early Exit item beside Adaptive under main page table and link to the notebook？

**Comment by XinyuYe-Intel** [comment]
> > > Where is the entry to get users to the notebook?
> > 
> > 
> > Where would you think it's suitable?
> 
> Is this about early exit? Add Early Exit item beside Adaptive under main page table and link to the notebook？

Yes, it's early exit. About Adaptive, do you mean here?
image

**Pull request merged**
