### PR TITLE
fixes to Neural Chat SparseBM25Retriever pipeline

### PR DESCRIPTION
**Pull request by kta-intel**
## Type of Change

bug fix
no change to API

## Description

Neural Chat SparseBM25Retriever pipeline had some minor typos that caused the code to error.

Specifically:
https://github.com/intel/intel-extension-for-transformers/blob/9491bbb8aa2b36a530abfcdc1155ffa17f3246f8/intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_bm25.py#L23

Should be `__init__`

and

https://github.com/intel/intel-extension-for-transformers/blob/9491bbb8aa2b36a530abfcdc1155ffa17f3246f8/intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py#L136

should be `self.document_store`

JIRA ticket: N/A

## Expected Behavior & Potential Risk

Using Neural chat with SparseBM25Retriever should successfully retrieve outputs from inputted documents without error-ing out

## How has this PR been tested?

Tested on AWS M7i EC2 instance - Intel(R) Xeon(R) Platinum 8488C
Run retrieval pipeline from [example](https://github.com/kta-intel/intel-extension-for-transformers/tree/kta-branch/intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval#import-the-module-and-set-the-retrieval-config) and set:
```
plugins.retrieval.args["retrieval_type"]="sparse"
plugins.retrieval.args["document_store"]="inmemory"
```

## Dependency Change?

None

### CODE REVIEW

**Comment by VincyZhang** [comment]
finetunint/inference chatbot tests failed due to can not checkout to fork repo when build docker image according to our dockerfile, https://github.com/kta-intel/intel-extension-for-transformers/blob/kta-sparse-neural-chat/intel_extension_for_transformers/neural_chat/docker/Dockerfile#L49

**Comment by kta-intel** [comment]
Thanks @VincyZhang, how can I go about resolving this in order to get it approved and merged?

**Comment by VincyZhang** [comment]
> [kta-intel](/kta-intel)

just update our docker build method in this PR https://github.com/intel/intel-extension-for-transformers/pull/427
let me update your branch

**Comment by VincyZhang** [comment]
I still encounter the same problem, let me explore more. @kta-intel For you PR, once the UT pass, I will merge for you.

**Pull request merged**
