### PR TITLE
[NeuralChat] Enable finetune for Qwen-7b-chat on CPU (WIP)

### PR DESCRIPTION
**Pull request by huiyan2021**
## Type of Change

Enable finetune for Qwen-7b-chat on CPU

## Description

add support for Qwen-7b-chat in llm/finetuning/finetuning.py

## Expected Behavior & Potential Risk

Finetune Qwen-7b-chat can be run on CPU

## How has this PR been tested?

Modify test code in intel_extension_for_transformers/neural_chat/tests/finetuning/test_finetuning.py

  def test_finetune_clm(self):
      # model_args = ModelArguments(model_name_or_path="facebook/opt-125m")
      model_args = ModelArguments(model_name_or_path="Qwen/Qwen-7B-Chat") 

## Dependency Change?

no

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Comment by hshen14** [comment]
@huiyan2021  can you please try below tasks using Qwen? You may check with @lkk12014402.

image

**Comment by huiyan2021** [comment]
will do

**Review by kevinintel — APPROVED** [review]

**Comment by VincyZhang** [comment]
@huiyan2021 Is this PR ready for merge?

**Comment by huiyan2021** [comment]
Only text generation (chat) has been validated for Qwen at the time being, need to validate for other tasks.

**Comment by huiyan2021** [comment]
@hshen14 @VincyZhang @kevinintel  

Validated for :  

<html>
<body>

Text Generation (Instruction) | Text Generation (ChatBot) | Summarization | Code Generation

</body>
</html>

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
