### PR TITLE
Dev/ipex woq

### PR DESCRIPTION
**Pull request by PenghuiCheng**
## Type of Change

bug fix and new feature
No API changed

## Description

Support loading shared safetensor model and fixed loading int4 model issue.

## Expected Behavior & Potential Risk

Load and save model successfully

## How has this PR been tested?

Local tested

### CODE REVIEW

**Review by zhenwei-intel — APPROVED** [review]

**Review by changwangss — APPROVED** [review]

**Comment by VincyZhang** [comment]
coverage drop even more
image

**Comment by VincyZhang** [comment]
image

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-optimize-ut/2820/

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/nlp-toolkit-optimize-ut/2824/

**Comment by VincyZhang** [comment]
coverage drop 1.3%
image

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/nlp-toolkit-optimize-ut/2828/

**Pull request merged**
