### PR TITLE
[LLM Runtime] Correct GCC targe options

### PR DESCRIPTION
**Pull request by DDEle**
## Type of Change: bug
API not changed

## Description
As title

## Expected Behavior & Potential Risk
N/A

## How has this PR been tested?
GitHub action checks.

In addition, it is locally tested that the performance impact of this PR to MHA (FLASH_ATTN_KV_UPDATE) is neglectable.

Before
image

After
image

## Dependency Change?
No

### CODE REVIEW

**Review by luoyu-intel — APPROVED** [review]
LGTM. Need to fix crash on avx2 device

**Comment by DDEle** [comment]
> LGTM. Need to fix crash on avx2 device

No crash with g32/g128

**Review by yuchengliu1 — APPROVED** [review]

**Comment by bearn01d** [comment]
I applied this patch and can confirm it indeed solves #675 . Also, the problem that the models only output garbage on the AMD machine is resolved with this PR.

**Comment by DDEle** [comment]
> I applied this patch and can confirm it indeed solves #675 . Also, the problem that the models only output garbage on the AMD machine is resolved with this PR.

Big thanks for your timely feedback!

**Review by zhewang1-intc — APPROVED** [review]
LGTM

**Comment by zhewang1-intc** [comment]
> LGTM. Need to fix crash on avx2 device

avx2 device crash due to target compile option pollution. already fixed in jblas 73cba

**Pull request merged**
