### PR TITLE
[API Changed] Dispatch the backend based on model_type

### PR DESCRIPTION
**Pull request by Zhenzhong1**
## Type of Change

API changed.

## Description

Select the backend(Neural Speed or Pytorch) based on model_type

## Expected Behavior & Potential Risk

N/A

## How has this PR been tested?

Manually

## Dependency Change?

N/A

### CODE REVIEW

**Review by changwangss — APPROVED** [review]

**Review by hshen14 — APPROVED** [review]

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1442/

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1443/

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/nlp-toolkit-validation-top-mr-extension/1446/

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/nlp-toolkit-validation-top-mr-extension/1448/

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
