### PR TITLE
[CPP Graph] Enhance beam search (length_penalty + min_new_tokens)

### PR DESCRIPTION
**Pull request by zhentaoyu**
## Type of Change

feature or bug fix or documentation or others
API changed or not: no

## Description

detail description 
JIRA ticket: [835](https://jira.devtools.intel.com/browse/NLPTOOLKIU-835)
**This PR only focuses the  ggml `q4_0` format**
TODO:
- [x] add length_penalty
- [x] add min_new_tokens
~~- [ ] early_stopping (optional?)~~
- [x] bad generated texts (kv cache reorder, inference, etc...)

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

`numactl -l -C 0-55 ./build/bin/pybind_gptj  fp32.bin/q4_0.bin`

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by zhentaoyu** [comment]
**main branch test ref (q4_0, machine6)**
`pybind_gptj` beam_search outputs, `n_predict = 128`:
1. turn on `MHA_FUSION` flag (default)

```bash
numactl -l -C 0-55 ./build/bin/pybind_gptj gptj_q40.bin
ARCH_REQ_XCOMP_PERM XTILE_DATA successful.
AVX:1 AVX2:1 AVX512F:1 AVX_VNNI:1 AVX512_VNNI:1 AMX_INT8:1 AMX_BF16:1 AVX512_FP16:1
model.cpp: loading model from gptj_q40.bin
init: n_vocab    = 50400
init: n_ctx      = 2048
init: n_embd     = 4096
init: n_mult     = 256
init: n_head     = 16
init: n_layer    = 28
init: n_rot      = 64
init: n_ff       = 16384
init: n_parts    = 1
load: ne ctx size =    0.07 MB
load: mem required  = 11770.36 MB (+ 4096.00 MB per state)
.
model_init_from_file: kv self size  = 3584.00 MB
She opened the door and see me standing there.




“


```

2. turn off 'MHA_FUSION' flag
```bash
numactl -l -C 0-55 ./build/bin/pybind_gptj gptj_q40.bin
ARCH_REQ_XCOMP_PERM XTILE_DATA successful.
AVX:1 AVX2:1 AVX512F:1 AVX_VNNI:1 AVX512_VNNI:1 AMX_INT8:1 AMX_BF16:1 AVX512_FP16:1
model.cpp: loading model from gptj_q40.bin
init: n_vocab    = 50400
init: n_ctx      = 2048
init: n_embd     = 4096
init: n_mult     = 256
init: n_head     = 16
init: n_layer    = 28
init: n_rot      = 64
init: n_ff       = 16384
init: n_parts    = 1
load: ne ctx size =    0.07 MB
load: mem required  = 11770.36 MB (+ 4096.00 MB per state)
.
model_init_from_file: kv self size  = 3584.00 MB
She opened the door and see me standing there. She said, like, "What the fuck are you doing here?"

I said, "I'm here to see you."

She said, "I'm not seeing anyone."

I said, "I'm not here to see you. I'm here to see your daughter."

She said, "I don't have a daughter."

I said, "I know you do. I know you do. I know you do."

She said, "I don't have a daughter."

I said, "I know you do. I know you do.

```
Later tests will turn off 'MHA_FUSION' flag (maybe `flash_attn` for first token only works for `q4_j` format)

**Comment by zhentaoyu** [comment]
test result of commit [51b46fe](https://github.com/intel/intel-extension-for-transformers/pull/173/commits/51b46fe652339614e7b703a4372cc18cd55322ba)

```bash
ARCH_REQ_XCOMP_PERM XTILE_DATA successful.
AVX:1 AVX2:1 AVX512F:1 AVX_VNNI:1 AVX512_VNNI:1 AMX_INT8:1 AMX_BF16:1 AVX512_FP16:1
model.cpp: loading model from gptj_q40.bin
init: n_vocab    = 50400
init: n_ctx      = 2048
init: n_embd     = 4096
init: n_mult     = 256
init: n_head     = 16
init: n_layer    = 28
init: n_rot      = 64
init: n_ff       = 16384
init: n_parts    = 1
load: ne ctx size =    0.07 MB
load: mem required  = 11770.36 MB (+ 4096.00 MB per state)
.
model_init_from_file: kv self size  = 3584.00 MB
A spaceship lands on the moon, and the first thing the astronauts do is to take a picture of the Earth.

The picture is taken by a camera on the spacecraft, and the image is transmitted to the Earth.

The picture is received by a television camera on the ground, and the picture of all of the moon is a good example of all, the moon is a pretty big place to land, so it is not only a few days before the moon landing, but the question of whether the moon is the first time I've seen this is a good example of how to make money online with the way back to the moonlighting the moon.

```

**Comment by zhentaoyu** [comment]
test result of commit [9c8fc64](https://github.com/intel/intel-extension-for-transformers/pull/173/commits/9c8fc640140a1c943562edb383b99c7a48ee3122)
different results because #181 quant `lm_head` by default.

`min_new_tokens` = 30, `length_penalty` = 1.0. `max_new_tokens` = 128

```bash
A spaceship lands on the moon. A spaceship lands on the moon. A spaceship lands on Mars. A spaceship lands on the moon. A spaceship lands on Mars. A spaceship lands on the moon. A spaceship lands on the moon.

A spaceship lands on Mars.

A spaceship lands on Mars. A spaceship lands on the moon.

A spaceship lands on Mars.

A spaceship lands on Mars.

A spaceship lands on Mars. A spaceship lands on Mars.

A spaceship lands on the moon. A spaceship lands on Mars. A spaceship lands on Mars.

A spaceship lands on the moon.

A spaceship


```

**Comment by zhentaoyu** [comment]
compare greedy search between `PyTorch` fp32 and `CPP Graph` fp32 results:  (`num_beams = 1`)
```python
from transformers import pipeline, set_seed, AutoModelForCausalLM, AutoTokenizer
model_dir = "gpt-j-6b"
tokenizer = AutoTokenizer.from_pretrained(model_dir)

model = AutoModelForCausalLM.from_pretrained(model_dir, dtype=torch.bfloat16)
model.eval()
prompt = "A spaceship lands on the moon"
inputs = tokenizer(prompt, return_tensors="pt")

print("inputs", inputs)
generate_ids = model.generate(inputs.input_ids, max_new_tokens=128, min_new_tokens=30, early_stopping=True, num_beams=1)
ans = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print(ans)
```
same outputs:
```bash
A spaceship lands on the moon. The first man to step out of the spacecraft is greeted by a group of scientists. They ask him, “What do you want?”

“I want to know what’s going on here,” he replies.

“We’re scientists,” they say. “We’re here to study the moon.”

“I’m a scientist, too,” he says. “I want to know what’s going on here.”

“We’re scientists,” they

```

**Comment by zhentaoyu** [comment]
long prompt test (original test case in `pybind_gptj.cpp`)
```bash
2017: It is done, and submitted. You can play 'Survival of the Tastiest' on Android, and on the web. Playing on the web works, but you have to simulate multiple touch for table moving and that can be a bit confusing. There is a lot I'd like to talk about. I will go through every topic, insted of making the typical what went right/wrong list. Concept Working over the theme was probably one of the hardest tasks which I had to face. Originally, I had an idea of what kind of game I wanted to develop, gameplay wise - something with a lot of enemies/actors, simple graphics, maybe set in space, controlled from a top-down view. I was confident that I could fit any theme around it. In the end, the problem with a theme like 'Evolution' in a game is that evolution is unassisted. It happens through several seemingly random mutations over time, with the most apt permutation surviving. This genetic car simulator is, in my opinion, a great example of actual evolution of a species facing a challenge. But is it a game? In a game, you need to control something to reach an objective. That control goes against what evolution is supposed to be like. If you allow the user to pick how to evolve something, it's not evolution anymore - it's the equivalent of intelligent design, the fable invented by creationists to combat the idea of evolution. Being agnostic and a Pastafarian, that's not something that rubbed me the right way. Hence, my biggest dillema when deciding what to create was not with what I wanted to create, but with what I did not. I didn't want to create an 'intelligent design' simulator and wrongly call it evolution. This is a problem, of course, every other contestant also had to face. And judging by the entries submitted, not many managed to work around it. I'd say the only real solution was through the use of artificial selection, somehow. So far, I haven't seen any entry using this at its core gameplay. Alas, this is just a fun competition and after a while I decided not to be as strict with the game idea, and allowed myself to pick whatever I thought would work out. My initial idea was to create something where humanity tried to evolve to a next level, but had some kind of foe trying to stop them from doing so. I kind of had this image of human souls flying in space towards a monolith or a space baby (all based in 2001: A Space Odyssey of course) but I couldn't think of compelling (read: serious) mechanics for that. Borgs were my next inspiration, as their whole hypothesis fit pretty well into the evolution theme. But how to make it work? Are you the borg, or fighting the Borg? The third and final idea came to me through my girlfriend, who somehow gave me the idea of making something about the evolution of Pasta. The more I thought about it the more it sounded like it would work, so I decided to go with it. Conversations with my inspiring co-worker Roushey (who also created the 'Mechanical Underdogs' signature logo for my intros) further matured the concept, as it involved into the idea of having individual pieces of pasta flying around and trying to evolve until they became all-powerful. A secondary idea here was that the game would work to explain how the Flying Spaghetti Monster came to exist - by evolving from a normal dinner table. So the idea evolved more or less into this: you are sitting a table. You have your own plate, with is your 'base'. There are 5 other guests at the table, each with their own plate. Your plate can spawn little pieces of pasta. You do so by 'ordering' them through a menu. Some pastas are better than others; some are faster, some are stronger. They have varying 'costs', which are debited from your credits (you start with a number of credits). Once spawned, your pastas start flying around. Their instinct is to fly to other plates, in order to conquer them (the objective of the game is having your pasta conquer all the plates on the table). But they are really autonomous, so after being spawned, you have no control over your pasta (think DotA or LoL creeps). Your pasta doesn't like other people's pasta, so if they meet, they shoot sauce at each other until one dies. You get credits for other pastas your own pasta kill. Once a pasta is in the vicinity of a plate, it starts conquering it for its team. It takes around 10 seconds for a plate to be conquered; less if more pasta from the same team are around. If pasta from other team are around, though, they get locked down in their attempt, unable to conquer the plate, until one of them die (think Battlefield's standard 'Conquest' mode). You get points every second for every plate you own. Over time, the concept also evolved to use an Italian bistro as its main scenario. Carlos, Carlos' Bistro's founder and owner Setup No major changes were made from my work setup. I used FDT and Starling creating an Adobe AIR (ActionScript) project, all tools or frameworks I already had some knowledge with. One big change for me was that I livestreamed my work through a twitch.tv account. This was a new thing for me. As recommended by Roushey, I used a program called XSplit and I got to say, it is pretty amazing. It made the livestream pretty effortless and the features are awesome, even for the free version. It was great to have some of my friends watch me, and then interact with them and random people through chat. It was also good knowing that I was also recording a local version of the files, so I could make a timelapse video later. Knowing the video was being recorded also made me a lot more self-conscious about my computer use, as if someone was watching over my shoulder. It made me realize that sometimes I spend too much time in seemingly inane tasks (I ended up wasting the longest time just to get some text alignment the way I wanted - it'll probably drive someone crazy if they watch it) and that I do way too many typos where writing code. I pretty much spend half of the time writing a line and the other half fixing the crazy characters in it. My own stream was probably boring to watch since I was coding for the most time. But livestreaming is one of the cool things to do as a spectator too. It was great seeing other people working - I had a few tabs opened on my second monitor all the time. It's actually a bit sad, because if I could, I could have spent the whole weekend just watching other people working! But I had to do my own work, so I'd only do it once in a while, when resting for a bit. Design Although I wanted some simple, low-fi, high-contrast kind of design, I ended up going with somewhat realistic (vector) art. I think it worked very well, fitting the mood of the game, but I also went overboard. For example: to know the state of a plate (who owns it, who's conquering it and how much time they have left before conquering it, which pasta units are in the queue, etc), you have to look at the plate's bill. The problem I realized when doing some tests is that people never look at the bill! They think it's some kind of prop, so they never actually read its details. Plus, if you're zoomed out too much, you can't actually read it, so it's hard to know what's going on with the game until you zoom in to the area of a specific plate. One other solution that didn't turn out to be as perfect as I thought was how to indicate who a plate base belongs to. In the game, that's indicated by the plate's decoration - its color denotes the team owner. But it's something that fits so well into the design that people never realized it, until they were told about it. In the end, the idea of going with a full physical metaphor is one that should be done with care. Things that are very important risk becoming background noise, unless the player knows its importance. Originally, I wanted to avoid any kind of heads-up display in my game. In the end, I ended up adding it at the bottom to indicate your credits and bases owned, as well as the hideous out-of-place-and-still-not-obvious 'Call Waiter' button. But in hindsight, I should have gone with a simple HUD from the start, especially one that indicated each team's colors and general state of the game without the need for zooming in and out. Development Development went fast. ------>(new_tokens here) I started coding the first version of the first version 0.1 was released on the first day of the competition. I was pretty proud of course. I had a lot of fun making this game. It's a lot of work to make something like this. It took a lot of time to get the graphics and the gameplay right, but I think I did a good enough to the right of the table, and I'my' pasta' is a good example of how to use of the word "A", and it was a good thing I did not know about it before. I think it's a good thing to do is to
```

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by zhentaoyu** [comment]
`PyTorch` fp32 v.s. `CPP Graph` fp32 under `num_beams = 4`
1st example:
`PyTorch` output:
```bash
A spaceship lands on the moon. It’s the first manned mission to the lunar surface, and it’s been a long time coming.

It’s been more than 50 years since the Apollo 11 mission landed on the moon in July 1969, and it’s been more than 40 years since the last manned mission to the lunar surface, Apollo 17, landed in December 1972.

NASA’s next manned mission to the moon, Artemis, is scheduled to launch in 2024, and it will be the first mission to [land humans on the lunar surface in more than four decades.

“It’s been
```

`CPP Graph` output:
```bash
A spaceship lands on the moon, and the first man’s surface, and a manuever, the moon is the first time I saw the moon I thought, ‘Oh, my god! It’s so big. It’s huge. It’s so big! It’s so huge. It’s huge. It’s huge! It’s so big.’ I thought it was so huge, and then I realized, ‘No, it’s not that big.’ It was a big moon. It’s not that big, but not all the
```

2nd example:
`prompt = "What is the meaning of life?"`
`PyTorch` output:
```bash
What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

What is the meaning of life?

```

`CPP Graph` output:
```bash
What is the meaning of life? This is a question that has been asked for centuries, and it is one of the most important questions of all the way from a philosophical point of view.

What is the meaning of life?

What is life? What is its meaning?

What is the meaning of life?

What is life?

What is life? What is the meaning of life?

What is the meaning of life?

What is the meaning of life? What is life?

What is life?

What is the meaning of life? What is life? What is life?

What is
```

The cause for different results will be investigated in another PR.

**Review by zhenwei-intel — APPROVED** [review]
LGTM

**Pull request merged**
