### PR TITLE
added .gitpod.yml  for config

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
added gitpod configuration file for gitpod users to easily deploy this repo in cloud

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@hshen14 kindly review and merge it

**Comment by hshen14** [comment]
CC @VincyZhang @kevinintel

**Comment by VincyZhang** [comment]
Hi @PentesterPriyanshu , forgive me I'm not familiar with gitpod, would you please explain why do we need to add this yml into our repo?  I thought it will only be needed when you create a gitpod project, why is it need to be included in a normal github repo?

**Comment by PentesterPriyanshu** [comment]
@VincyZhang this is configuration file like someone wants to contribute in repo instead of cloning the repo locally ,
it is cloud based environment so instead of cloning we can deploy the whole repo and this configuration file will install all dependencies in gitpod then we can work it on 
i have added this as in many opensource project people will now avoid cloning whole repo they just do all the things in cloud which saves time 
thankyou, if you want to know more about gitpod or cloud services i can explain you further but this is basic just to understand that what this file does

**Review by VincyZhang — APPROVED** [review]

**Comment by PentesterPriyanshu** [comment]
@kevinintel i need time i will show that too but dont merge this pr now as now it is showing some issues i fix it today then you can merge

**Comment by PentesterPriyanshu** [comment]
@kevinintel  just signup on gitpod and open its webextension you can see all dependencies will be downwloaded automatically

**Comment by kevinintel** [comment]
I check the description of this yml: https://www.gitpod.io/docs/references/gitpod-yml.
It need build instruction, please raise it i another PR.

**Review by kevinintel — APPROVED** [review]

**Review by kevinintel — CHANGES_REQUESTED** [review]
please remove app.py

**Review by kevinintel — APPROVED** [review]

**Comment by PentesterPriyanshu** [comment]
merge it

**Pull request merged**
