### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RS-labhub**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by RS-labhub** [comment]
@VincyZhang please review this.. Conflicts are solved

**Review by hshen14 — APPROVED** [review]

**Comment by hshen14** [comment]
> @VincyZhang please review this.. Conflicts are solved

It seems the format is broken. Can you please check whether there is sth wrong during the conflict solving?

**Comment by RS-labhub** [comment]
> > @VincyZhang please review this.. Conflicts are solved
> 
> It seems the format is broken. Can you please check whether there is sth wrong during the conflict solving?

Done perhaps!

**Comment by hshen14** [comment]
> > > @VincyZhang please review this.. Conflicts are solved
> > 
> > 
> > It seems the format is broken. Can you please check whether there is sth wrong during the conflict solving?
> 
> Done perhaps!

Seems not. You can probably remove "=======" caused by previous conflict?

**Comment by RS-labhub** [comment]
> > > > @VincyZhang please review this.. Conflicts are solved
> > > 
> > > 
> > > It seems the format is broken. Can you please check whether there is sth wrong during the conflict solving?
> > 
> > 
> > Done perhaps!
> 
> Seems not. You can probably remove "=======" caused by previous conflict?

Did.. Thanks for telling

**Review by hshen14 — APPROVED** [review]

**Review by VincyZhang — APPROVED** [review]

**Comment by VincyZhang** [comment]
@RS-labhub  If there is no more update, I will merge this PR. Thanks!

**Comment by RS-labhub** [comment]
> @RS-labhub If there is no more update, I will merge this PR. Thanks!

Thank you so much!!!! Learned a lot! Really thankful to you.

**Pull request merged**
