### PR TITLE
[NeuralChat] support return error code

### PR DESCRIPTION
**Pull request by lvliang-intel**
## Type of Change

feature
API changed

## Description

Support return error code for build_chatbot, predict and predict_stream.

## Expected Behavior & Potential Risk

Users can check the error code to identify the root cause of the issues.

## How has this PR been tested?

Local test and pre-CI test.

## Dependency Change?

None.

### CODE REVIEW

**Comment by VincyZhang** [comment]
Unit Test failed with lines coverage decrease -0.861%
Unit Test failed with branches coverage decrease -1.162%

**Comment by VincyZhang** [comment]
Do we need to check intel_extension_for_transformers/neural_chat when calculating coverage of optimize UT? @lvliang-intel  @PenghuiCheng

**Review by hshen14 — APPROVED** [review]

**Review by ftian1 — APPROVED** [review]

**Comment by ftian1** [comment]
The preci failure is due to ~1% line coverage downgrade. @VincyZhang is it ok to merge?

**Comment by hshen14** [comment]
> The preci failure is due to ~1% line coverage downgrade. @VincyZhang is it ok to merge?

Discussed with @lvliang-intel, he will improve the coverage in a separate PR.

**Pull request merged**
