### PR TITLE
Fix SQ baichuan without position_ids for torch and ipex 2.3.0

### PR DESCRIPTION
**Pull request by changwangss**
## Type of Change
ticket: https://jira.devtools.intel.com/browse/ILITV-3631
ipex 2.3.0 optimized baichuan 13b without position_ids, so remove it.
meantime, ipex 2.3.0 offically supported transformers 4.38.1, so change the tuning and benchmark files.
update ipex 2.3.0 optmize llm supported list.
remove llama version limit when transformers higher than 4.36
## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1635/

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1637/

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/7810/
https://inteltf-jenk.sh.intel.com/job/nlp_toolkit_optimize_validation_localtest/7811/

**Review by XuehaoSun — APPROVED** [review]

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1646/
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1647/

**Pull request merged**
