### PR TITLE
[Transformers] Refine Model `from_pretrained` When `use_neural_speed`

### PR DESCRIPTION
**Pull request by zhentaoyu**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
JIRA ticket: xxx
- fp32 model in, fp32 dtype inference
   ```python
   itrex_model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=None, use_neural_speed=True, 
                              trust_remote_code=True)
   itrex_generate_ids = itrex_model.generate(inputs.input_ids, do_sample=False, max_new_tokens=100)[0]
   ```
- fp32 model in, low-bits dtype inference
  ```python
  woq_config=RtnConfig(compute_dtype="int8", weight_dtype="int4", group_size=128)
  itrex_model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, use_neural_speed=True,  
   trust_remote_code=True)
  itrex_generate_ids = itrex_model.generate(inputs.input_ids, do_sample=False, max_new_tokens=100)[0]
  ```
- low-bits model in, low-bits dtype inference
  ```python
  model_name = "Intel/Mistral-7B-v0.1-int4-inc"
  itrex_model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=None, use_neural_speed=True, 
    trust_remote_code=True)
  itrex_generate_ids = itrex_model.generate(inputs.input_ids, do_sample=False, max_new_tokens=100)[0]
  ```

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by a32543254** [comment]
please also change tests/Nightly/test_llm_runtime.py

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1504/

**Comment by ftian1** [comment]
@zhentaoyu  the README file in the root dir also should be refined to reflect this change

**Comment by zhentaoyu** [comment]
> @zhentaoyu the README file in the root dir also should be refined to reflect this change

done

**Comment by zhentaoyu** [comment]
`test_neural_speed.test_llm_runtime`  pass
image

`test_neural_speed.test_beam_search` pass
image

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by hshen14 — APPROVED** [review]

**Review by changwangss — APPROVED** [review]

**Pull request merged**
