### PR TITLE
[Engine]QAT Stable Diffusiomn Enabling

### PR DESCRIPTION
**Pull request by Zhenzhong1**
## Type of Change

Feature Add

## Description

Add QAT INT8 stable diffusion example.

## Expected Behavior & Potential Risk

N/A

## How has this PR been tested?

test ut-engine

## Dependency Change?

N/A

### CODE REVIEW

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by Zhenzhong1** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1270/

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by zhentaoyu — APPROVED** [review]
LGTM

**Pull request merged**
