### PR TITLE
fix : init_from_bin example

### PR DESCRIPTION
**Pull request by park12sj**
## Type of Change

If model.tokenizer is not specified, an error occurs in the line below when running `model.genreate`.
https://github.com/intel/intel-extension-for-transformers/blob/e33f2f7a635a08a625b1fae7b8c3a1f2c5799ce3/intel_extension_for_transformers/llm/runtime/graph/__init__.py#L201-L204
```
Traceback (most recent call last):
  File "/workspace/storage/cephfs-personal/git/pai/ml/ml/model/application/nlp/place_lm/inference/benchmarks/evaluate_performance.py", line 77, in evaluate_performance
    batch_inference_results = batch_inference(
  File "/workspace/storage/cephfs-personal/git/pai/ml/ml/model/application/nlp/place_lm/inference/acceleration/05_cpu_itrex/evaluate.py", line 114, in batch_inference
    generated = model.generate(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/__init__.py", line 188, in generate
    elif ret[0][-1] == self.eos_token_id() or \
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/intel_extension_for_transformers/llm/runtime/graph/__init__.py", line 202, in eos_token_id
    if self.tokenizer.eos_token_id == None:
AttributeError: 'Model' object has no attribute 'tokenizer'
```

## Description

detail description 
JIRA ticket: xxx

### CODE REVIEW

**Comment by zhenwei-intel** [comment]
tokenizer is loaded automatically : https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/runtime/graph/__init__.py#L80

**Comment by zhenwei-intel** [comment]
> hi @park12sj,
> 
> `tokenizer` is loaded automatically : https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/runtime/graph/__init__.py#L80
> 
> Can you check if you have this initialization code?

I misunderstood what you meant. You are right. If you use the init_from_bin interface, there is indeed a lack of tokenizer. But now you can basically do it through the init interface.

**Review by zhenwei-intel — APPROVED** [review]

**Comment by airMeng** [comment]
@park12sj would you fix https://github.com/intel/intel-extension-for-transformers/pull/786#discussion_r1406983002 in this PR?

**Review by airMeng — APPROVED** [review]

**Comment by zhentaoyu** [comment]
Hi, the `init_from_bin` (this API will be hidden in the model class) issue has been fixed in https://github.com/intel/intel-extension-for-transformers/pull/794. Thanks.

**Comment by park12sj** [comment]
Thank you for noti. 
I'll save only the part that fixes the issue. https://github.com/intel/intel-extension-for-transformers/pull/786#discussion_r1406983002

**Pull request merged**
