### PR TITLE
Added license section

### PR DESCRIPTION
**Pull request by dalvishruti14**
## Type of Change
Documentation

API changed or not
No

## Description
I have added a hyperlink to the license in the readme file. This improvement will make it easier for users and contributors to access the project's license for reference.

JIRA ticket: xxx

## Expected Behavior & Potential Risk
This change does not introduce any functional or code changes.

## How has this PR been tested?
Testing is not required for this documentation update

## Dependency Change?
No

### CODE REVIEW

**Comment by dalvishruti14** [comment]
closes #587

**Comment by hshen14** [comment]
Please follow the instructions in https://github.com/intel/intel-extension-for-transformers/pull/588/checks?check_run_id=18191804114 to pass DCO checker.

**Comment by kevinintel** [comment]
Hi dalvishruti14,
please pass DCO checker, we will merge it soon

**Comment by dalvishruti14** [comment]
> Hi dalvishruti14, please pass DCO checker, we will merge it soon

yes will do

**Comment by dalvishruti14** [comment]
@kevinintel @hshen14 passes dco checker

**Review by hshen14 — APPROVED** [review]

**Pull request merged**
