### PR TITLE
Support load_in_4bit and load_in_8bit on CPU device

### PR DESCRIPTION
**Pull request by changwangss**
## Type of Change
the usage is the same with transformers, BitsAndBytesConfig(load_in_tbit, load_in_8bit, compte_dypt)  -> advance usage (PR xx)

extend cpu device support base transformers, from_pretrained(load_in_4bit， load_in_8bit)  -> load_in_4bit is one recipes of BitsAndBytesConfig()

support load_in_4bit and load_in_8bit.
add awq,teq calib_func, calib_dataloader, remove gptq parser on text-generation due to qbit doesn't support gptq.
BitsAndBytes need GPU device, so remove from the validation list.

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1332/console

**Comment by hshen14** [comment]
Do we have examples/tests to have a meaningful check for BitsAndBytes? We can probably reserve a NV T4 from Azure?

**Comment by changwangss** [comment]
> Do we have examples/tests to have a meaningful check for BitsAndBytes? We can probably reserve a NV T4 from Azure?

I have the example, with args "--bitsandbytes" to check, the device maybe need confirm with @VincyZhang

**Comment by VincyZhang** [comment]
> > Do we have examples/tests to have a meaningful check for BitsAndBytes? We can probably reserve a NV T4 from Azure?
> 
> I have the example, with args "--bitsandbytes" to check, the device maybe need confirm with @VincyZhang

We can use our local/cloud GPU for extension test first

**Review by PenghuiCheng — APPROVED** [review]

**Review by xin3he — APPROVED** [review]

**Review by hshen14 — APPROVED** [review]

**Comment by changwangss** [comment]
load_in_4bit, load_in_8bit, ipex: https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1338/
mixedprecision: https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1339/

**Pull request merged**
