### PR TITLE
doc: add example for autoround and llama3 on intel gpu

### PR DESCRIPTION
**Pull request by zhenwei-intel**
## Type of Change

documentation
API changed or not

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by kevinintel — COMMENTED** [review]
add link of autoround parameters

**Comment by zhenwei-intel** [comment]
> add link of autoround parameters

added in https://github.com/intel/intel-extension-for-transformers/pull/1491/commits/a277554b8cec11b961e5f5c8ca2e6ff900d54b32

**Comment by kevinintel** [comment]
> > add link of autoround parameters
> 
> added in [a277554](https://github.com/intel/intel-extension-for-transformers/commit/a277554b8cec11b961e5f5c8ca2e6ff900d54b32)

Remove the commit number part

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by kevinintel — APPROVED** [review]

**Pull request merged**
