### PR TITLE
[LLM Runtime] Update README

### PR DESCRIPTION
**Pull request by zhenwei-intel**
## Type of Change

document

## Description

https://github.com/intel/intel-extension-for-transformers/issues/694

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Review by Zhenzhong1 — APPROVED** [review]
Looks Good!

**Comment by airMeng** [comment]
https://github.com/intel/intel-extension-for-transformers/pull/437#discussion_r1395556064

consider to resolve this

**Review by airMeng — APPROVED** [review]

**Comment by zhenwei-intel** [comment]
> [#437 (comment)](https://github.com/intel/intel-extension-for-transformers/pull/437#discussion_r1395556064)
> 
> consider to resolve this

update f00869b91d8492d02e585c50144026eccbea5b3e

**Review by a32543254 — APPROVED** [review]
LGTM

**Pull request merged**
