### PR TITLE
[Documentation] upload streaming llm video

### PR DESCRIPTION
**Pull request by zhenwei-intel**
## Type of Change

documentation

## Description

upload streaming llm video

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by a32543254** [comment]
Nice expression for our features, we should prepare more easy understood video to show our features/API

**Comment by airMeng** [comment]
I think streaming llm should refer to that we will handle online requests more efficiently, but seems the video just shows more outputs?

**Review by hshen14 — APPROVED** [review]

**Comment by hshen14** [comment]
> I think streaming llm should refer to that we will handle online requests more efficiently, but seems the video just shows more outputs?
The technical can be applied to multi-turn chat, but the chat may have its own logic to deal with the max context so people may not be aware of such big difference: crash vs. streaming in this video.

**Review by airMeng — APPROVED** [review]

**Comment by airMeng** [comment]
> I think streaming llm should refer to that we will handle online requests more efficiently, but seems the video just shows more outputs?

streaming here refers to infinity context, my fault

**Pull request merged**
