### PR TITLE
fix the dolly failed

### PR DESCRIPTION
**Pull request by a32543254**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by VincyZhang** [comment]
dolly extension：https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/nlp-toolkit-validation-top-mr-extension/1316/

**Review by airMeng — COMMENTED** [review]
what is this for

**Comment by a32543254** [comment]
> what is this for

for this jira https://jira.devtools.intel.com/browse/NLPTOOLKIU-857

**Comment by a32543254** [comment]
> what is this for

we found one transformers' api in this example is deprecated, because of updating the transformers version from 4.28 to 4.33 
which is "adjust_logits_during_generation"
so we just remove this api and keep nightly test keep pass.

**Pull request merged**
