### PR TITLE
[LLM Runtime] Baichuan13B inference bug fix

### PR DESCRIPTION
**Pull request by Zhenzhong1**
## Type of Change

Bug fix

## Description

Baichuan13B Bug fix

## Expected Behavior & Potential Risk

This bug will only occur when FFN is not used.

## How has this PR been tested?

Manually and CI tests.

## Dependency Change?
N/A

### CODE REVIEW

**Review by airMeng — APPROVED** [review]
how can this work before?

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by a32543254** [comment]
> how can this work before?

In the past the FFN fusion is enabled as default, so this bug is not show up.

**Comment by intellinjun** [comment]
The scripts for convert baichuan and chatglm are not supported in the latest transformers, but we write in the README with the latest transformers, which should be fixed

**Review by zhenwei-intel — APPROVED** [review]

**Pull request merged**
