### PR TITLE
[Reorg Folder] reorg transformers and langchain folders

### PR DESCRIPTION
**Pull request by zhentaoyu**
## Type of Change

as title

## Description

detail description 
JIRA ticket: xxx
image

1. `llm/ --> transformers/llm`
2. `setfit/ --> transformers/setfit`
3. add `GenAI` in `examples`
4. add [llama_index](https://github.com/run-llama/llama_index/tree/main/llama-index-core/llama_index/core)
    ```bash
    llama_index/
         __init__.py
    ```
5. add [haystack](https://github.com/deepset-ai/haystack/tree/main/haystack/components)
    ```bash
   hay_stack/
        __init__.py
    ```
6.  rename `langchain` to [langchain_community](https://github.com/langchain-ai/langchain/tree/master/libs/community)
    
  ```bash
   langchain/
      langchain_community/  <older langchain folder>
          __init__.py
         embeddings/
         xxx
   ```
 
   usage: 
               `import intel_extension_for_transformers.langchain_community.embeddings as e`

7. `llm/runtime/deprecated ---> runtime/` and remove `llm/runtime/neural_speed`
8. remove useless files in `utils` folder and rename it to `tools`.

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by zhentaoyu** [comment]
`neural_chat tts_chinese` ut failure (reason is unknown, paddlepaddle related) may be solved by this pr: https://github.com/intel/intel-extension-for-transformers/pull/1139

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by VincyZhang — APPROVED** [review]

**Comment by VincyZhang** [comment]
CI-summary failed due to too many files changed, exceed maximum of github comment, but is not caused by this PR.
image

**Comment by ftian1** [comment]
1. should leave `llama-index` and `haystack` folder empty. only contain a __init__.py
2. should remove content in `utils` folder. put `carbon_calc.py` to `tools` folder and remove others.

**Comment by zhentaoyu** [comment]
> 1. should leave `llama-index` and `haystack` folder empty. only contain a **init**.py
> 2. should remove content in `utils` folder. put `carbon_calc.py` to `tools` folder and remove others.

done

**Review by ftian1 — APPROVED** [review]
looks good to me

**Pull request merged**
