### PR TITLE
[NeuralChat] Enhance Retrieval UTs

### PR DESCRIPTION
**Pull request by xmx-521**
## Type of Change

unit testing
API not changed

## Description

Restructure the Retrieval-related UTs in `intel_extension_for_transformers/neural_chat/tests/ci` to `intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval`.
Add UTs for format type: `csv`, `markdown`, `html`, `pdf`.
Add UTs for parameters: `response_template`, `mode`, `process`, `max_chuck_size`, `min_chuck_size`, `search_type`, `search_kwargs`.

## Expected Behavior & Potential Risk

Restructured UTs are equivalent to the previous Retrieval-related UTs.
Newly added UTs test the retrieval plugin well as expected.

## How has this PR been tested?

Local test and pre-CI

## Dependency Change?

None

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]
File extension is one dimension to check the retrieval. Shall we also consider the content category, e.g., plain text, OCR, image, video, table, other objects under html?

**Comment by XuhuiRen** [comment]
> File extension is one dimension to check the retrieval. Shall we also consider the content category, e.g., plain text, OCR, image, video, table, other objects under html?

That kind of feature could be done after the OCR is ready. video may be not easy to support

**Review by XuhuiRen — APPROVED** [review]

**Comment by VincyZhang** [comment]
@xmx-521  @XuhuiRen ready for merge?

**Comment by xmx-521** [comment]
> @xmx-521 @XuhuiRen ready for merge?



> @xmx-521 @XuhuiRen ready for merge?

yes

**Pull request merged**
