### PR TITLE
[NeuralChat] Fix Qwen chat model output undesirable on HPU issue caused by input padding

### PR DESCRIPTION
**Pull request by XinyuYe-Intel**
## Type of Change

bug fix
API not changed

## Description

Fix Qwen chat model output undesirable on HPU issue caused by input padding.
JIRA ticket: xxx

## Expected Behavior & Potential Risk

pass test 

## How has this PR been tested?

UT

## Dependency Change?

no library dependency introduced or removed

### CODE REVIEW

**Comment by sywangyi** [comment]
could you elaborate more on the issue? this change will cause recompile graph for hpu if input prompt length change.

**Comment by XinyuYe-Intel** [comment]
> could you elaborate more on the issue? this change will cause recompile graph for hpu if input prompt length change.

For [Qwen/Qwen-7B-Chat](https://huggingface.co/Qwen/Qwen-7B-Chat) as an example, when gave model the prompt "你好", if the input token is padded, it outputs nothing, if input token is not padded, it outputs "你好！有什么我能帮助你的吗？".

PS:
```
padded input: 
tensor([[151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151644,   8948,    198,   2610,    525,    264,  10950,  17847,     13,
         151645,    198, 151644,    872,    198, 108386, 151645,    198, 151644,
          77091,    198]], device='hpu:0')
```
model output of padded input: 
image


```
unpadded input: 
tensor([[151644,   8948,    198,   2610,    525,    264,  10950,  17847,     13,
         151645,    198, 151644,    872,    198, 108386, 151645,    198, 151644,
          77091,    198]], device='hpu:0')
```
model output of unpadded input: 
image

**Comment by sywangyi** [comment]
so does Qwen not support padding in generation? is the pad token correct? Qwen specific?

**Comment by sywangyi** [comment]
it is weird that Qwen does not support left padding in generation. if you batch 2 different lengths of prompt together and text generation with bs=2, what will happen with the smaller length of prompt.

**Comment by XinyuYe-Intel** [comment]
> it is weird that Qwen does not support left padding in generation. if you batch 2 different lengths of prompt together and text generation with bs=2, what will happen with the smaller length of prompt.

I've checked [Qwen's repo](https://github.com/QwenLM/Qwen?tab=readme-ov-file#batch-inference) and found that for batched generation with padding, we need to set pad token id to 151646 manually, after this, padded input also works. I will change `model.generation_config.pad_token_id` instead of `padding= "max_length"`.
image

**Comment by sywangyi** [comment]
so, the generation_config.json in Qwen is incorrect.

**Comment by XinyuYe-Intel** [comment]
> so, the generation_config.json in Qwen is incorrect.

Yes, I think so, also I find that output of [Qwen/Qwen-14B-Chat](https://huggingface.co/Qwen/Qwen-14B-Chat) is undesirable even with 151646 as pad_token_id.
model output of padded input:
image
model output of unpadded input:
image

**Review by sywangyi — APPROVED** [review]

**Pull request merged**
